export const GET_SCHEDULES = 'GET_SCHEDULES';
export const SAVE_SCHEDULES = 'SAVE_SCHEDULES';
export const GET_ALL_SCHEDULES = 'GET_ALL_SCHEDULES';
export const SAVE_ALL_SCHEDULES = 'SAVE_ALL_SCHEDULES';